name: locapp_front
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  geolocator: ^12.0.0
  google_maps_flutter: ^2.6.1
  cupertino_icons: ^1.0.6 
  animated_bottom_navigation_bar: ^1.0.1
  image_picker: ^0.8.4+3
  flutter_rating_bar: ^4.0.1
  intl: any
  flutter_localizations:
     sdk: flutter
  firebase_ui_auth: ^1.15.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

assets:
   - assets/images/
